fragment CarBrandData on CarBrand {
  id
  name
}

query GetBrands {
  carBrands {
    ...CarBrandData
  }
}

mutation CreateBrand($name: String!) {
  createCarBrand(name: $name) {
    id
    name
  }
}

mutation EditBrands($data: CarBrandData!) {
  editCarBrand(data: $data) {
      id
      name
    }
}

query GetModel($brandId: ID!) {
  carModels(brandId: $brandId) {
    brand {
      id
      name
    }
    id
    name
  }
}

mutation CreateModel($name: String!, $brandId: ID!) {
  createCarModel(name: $name, brandId: $brandId) {
    brand {
      id
    }
    name
  }
}

mutation EditModel($data: CarModelData!) {
  editCarModel(data: $data) {
      id
      name
  }
}

query GetModifications {
  carModifications(modelId: 3) {
    id
    model {
      brand {
        name
      }
      name
    }
    name
    horsePower
    weight
  }
}

query GetModification {
  allCarModifications {
    model {
      brand {
        id
        name
      }
      id
      name
      }
    id
    name
    coupe
    horsePower
    weight
  }
}

mutation CreateModification($name: String!, $modelId: ID!) {
  createCarModification(name: $name, modelId: $modelId) {
    model {
      id
      name
      brand {
        id
        name
      }
    }
    name
    coupe
    horsePower
    weight
  }
}

mutation EditModificatio($data: CarModificationData!) {
  editCarModification(data: $data) {
    id
    name
    coupe
    horsePower
    weight
  }
}

mutation DeleteModification($id: ID!) {
  deleteCarModification(id: $id)
}